print('')
print('='*200)
print('APRESENTAÇÃO DOS ELEMENTOS DE UM TRAPÉZIO x ')
B=float(input('Digite um valor para a base maior:  '))
b=float(input('Digite um valor para base menor: '))
h=float(input('Digite um valor para a altura: '))
a= (b+B)*h/2 
print('A base maior apresentada pelo usuário é {}cm'.format(B))
print('A base menor apresentada pelo usuário é {}cm'.format(b))
print('A altura apresentada pelo usuário é {}cm'.format(h))
print('A área do trapézio x com base os valores digitados pelo usuário será {}'.format(a))
print('='*200)
print('www.Matemática_no_papel.com.br')
print('Youtube:@Matemáticanopapel')
print('Instagram:@Prof_ÍtaloBenfica')