n=input('Digite Algo:')
print('\033[31m O seu tipo primitivo é:', type(n))
print('\033[32m É um número?:',n.isnumeric())
print('\033[33m Só tem espaços?:',n.isspace())
print('\033[34m É alfabético?:',n.isalpha())
print('\033 [35m É alfanumérico?:',n.isalnum())
print('\033 [36m Está em maiusculo?:',n.isupper())
print('\033 [37m Está em minúsculo?:',n.islower())
print('\033 [36m Está capitalizado?:',n.istitle())
