print('=-'*200)
print('TABELA DE TIMES BRASILEIRÃO SÉRIE A 2024- BETANO')
brasileirao=('Flamengo','Bahia','Botafogo','São Paulo','Athletico Paranaense','Red Bull Bragantino','Palmeiras','Internacional','Cruzeiro','Atlético Minério','Fortaleza','Juventude','Gremio','Vasco da Gama','Fluminense','Criciúma','Corínthians','Atlético Goianiense','Vitória','Cuiabá')
print(f'Lista de times Brasileirão Série A {brasileirao}')
print('=-'*100) 
print(f'Os times que estão no G4 do Brasileirão Série A Betano são:  {brasileirao[0:5]}')
print('=-'*100) 
print(f'Os times que estão na lanterna são: {brasileirao[0:5]}')
print('=-'*100) 
print(f'Os times em ordem alfabética são: {sorted(brasileirao)}')